version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
  api:
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: api
    ports:
      - '3000:4000'
volumes:
  mongo: